### ISSUE TITLE
Update Documentation regarding HHVM

### ISSUE THREAD

**Issue by thiagodebastos** [roots/bedrock-ansible#144]
To prevent sinking into a rabbit-hole as I had:
https://discourse.roots.io/t/cannot-connect-to-database/3299/11

I suggest letting users know that this is experimental, because I am new to this I assumed it was something that was under control.

This was my first time using ansible and I had no idea HHVM was a new thing, I switched it to true after hearing so much good about it and completely forgot that I had. 
This lead to database errors on vagrant.
One of which is the recreation of issue #73 whereby changing `mysql_root_password` in `group_vars - development` lead to errors. 
The other being that even if the db settings were left at default, the vagrant box would still fail to connect to the db socket: `Warning: mysql_connect(): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`

**Comment by swalkinshaw** [comment]
Apologies for the trouble.

#73 is a known bug obviously which should just be fixed. Basically I never wanted to document the bug because that's just silly when I told myself I'd fix it long ago... :(

The HHVM bug was a perfect storm of timing. When I developed and tested the feature it worked perfectly. In the few days between that and actually merging it in, HHVM released a new version which has a bug. See https://github.com/roots/bedrock-ansible/pull/145 for details.

**Comment by thiagodebastos** [comment]
Ah thanks for that! It's that looming shadow over our heads :+1: 
I don't think any of us realise that a developer/designer is acually a modern cleaner, just in the digital world hehe. I think I do more `cleaning things` than I do designing. I keep hoping the ratio will drop with experience.
