### ISSUE TITLE
Okay it says my VM is running using vagrant... now what?

### ISSUE THREAD

**Issue by joshuairl** [roots/bedrock-ansible#173]
I read this is Bedrock recommendation for development environment and I followed the instructions and configured it... how do I see my site locally on my Mac?
Where do I make changes? In my ~/Projects/my_site directory? or somewhere else?

Not much documentation for people who are new to ansible I guess?

**Comment by fullyint** [comment]
Congrats on getting it running!

You can use discourse.roots.io/ for support requests, rather than the issue tracker here.

>how do I see my site locally on my Mac?

You should be able to see your site in your browser at `example.dev`, or whatever site name you entered in `group_vars/development`. If it doesn't load, you might double-check that your site is in your `etc/hosts` file, and consider using the [vagrant-hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) plugin.

>Where do I make changes?

You can edit your files like normal on your local machine. Vagrant shares those files/folders, so your changes will show up in the VM and in your browser on refresh.

**Comment by joshuairl** [comment]
I assumed this much, I think I’m getting closer to debugging the issue.
Thanks for your help and the recommendation for the roots discourse.
Very helpful.
