### ISSUE TITLE
Deploy build commands

### ISSUE THREAD

**Issue by swalkinshaw** [roots/bedrock-ansible#179]
Look into two improvements:

* Local/remote commands should be together
* Add local post build commands

Right now the `pre_build_commands_local` aren't run right before the remote ones are. They are separated by other tasks: https://github.com/roots/bedrock-ansible/blob/2acf17739ad9702baedba2def0840a13cb8a27e1/roles/deploy/tasks/main.yml#L25-L44

These should probably be done one after another.

There's no local version of the `post_build_commands`. For consistency purposes there should be.

/cc @fullyint

**Comment by fullyint** [comment]
>Local/remote commands should be together

I was thinking of `pre_build_commands_local` as primarily used to compile theme assets locally, which would need to happen before sending those assets to the remote via the "Copy project files" task, which is the next task, at present. And, I figured it might typically be best to run `pre_build_commands` on the remote after you've copied up any files, and maybe after you've placed templates. That rationale would argue for keeping the current task sequence. But you're probably thinking of scenarios that I've failed to anticipate.

> Add local post build commands

I considered local post build commands, but deliberately left them out because I couldn't think of any examples of what they might be... but I'm guessing you can.

**Comment by swalkinshaw** [comment]
re: `pre_build_commands_local`

I realized why it was before copy project files, I just thought it was more consistent to have `pre_build_commands` there as well. Although the f500 role has it after.

re: `post_build_commands_local`

The only use case I had in mind was deploy notifications for services like Hipchat and Slack. But I realized those would have to be done after finalize anyway.

Also I'm not even sure how to nicely do this because ideally a user could just specify some simple role/playbook but as far as I know there isn't a nice way to dynamically include these.

Going to close this.

**Comment by fullyint** [comment]
@swalkinshaw I hadn't thought of moving `pre_build_commands` earlier (before the sync), to be next to `pre_build_commands_local`. Sounds fine, and has that consistent feel. I guess the downside would just be that it wouldn't accommodate the person who, for some reason, wants to run `pre_build_commands` (remote) using files they plan to sync up (sync wouldn't have happened yet).

Here's a potentially good alternative approach: We could make the very first and very last tasks local tasks, kind of like a round trip. You start with `pre_deploy_local_commands`, then go remote (deploy_helper init through deploy_helper finalize), then return home to local and do your `post_deploy_local_commands`.

That might be conceptually intuitive for people. It also ensures they have these tasks to "hook" into if they want. (And I can rest assured that future support questions about the missing post deploy hook won't have the sad answer, "Well @fullyint couldn't really think why you'd want the hook, so it isn't there.")

**Comment by swalkinshaw** [comment]
But doesn't `pre_build_commands_local` need to be after the deploy_helper `init` and before "Copy project files"? As you said it's dependent on that due to the use of `synchronize`.

**Comment by fullyint** [comment]
I can't think of any reason why the `pre_build_commands_local` can't come before deploy_helper `init`. There's no dependency I can think of. The `pre_build_commands_local` task doesn't use any of the `deploy_helper` attributes/data.

Of course, the sync task must come after both tasks above, so that assets are compiled and ready to sync, and because the sync task uses  `deploy_helper.new_release_path`.

So, I was just thinking you give a hook for local commands at the very beginning, before anything else, then a final hook for local commands at the very end, after everything else. Sorry if I'm missing something.

**Comment by swalkinshaw** [comment]
Nope, I was just conflating the two separate commands. I'll give it some thought but I'm less concerned without the equivalent `post_build_commands_local` as well.

**Comment by fullyint** [comment]
Ok cool. 

I'll obsess on it more, though... If you keep the pre-build local hook task after the deploy_helper init, people's local commands would have available to them the deploy helper data/variables, like release name. 

And related, if you add a registered variable to the "Clone project files" task, it would make available the before and after SHA for the project in the `shared/source` path (e.g., `registered_var.before` and `registered_var.after`). People's pre-build local commands could have this info available too, obviously so long as the pre-build local hook task comes after the cloning.

Ok, I'll stop this and go look at your latest commit.
