### ISSUE TITLE
MariaDB apt_repository failed with UK repo

### ISSUE THREAD

**Issue by rossey** [roots/bedrock-ansible#185]
When adding the MariaDB Ubuntu repo for my nearest mirror the `apt_repository` module failed:

    W: Failed to fetch http://mirrors.coreix.net/mariadb/repo/10.0/ubuntu/dists/trusty/main/i18n/Translation-en_US  Unable to connect to mirrors.coreix.net:http: [IP: 85.13.241.50 80]
    W: Failed to fetch http://mirrors.coreix.net/mariadb/repo/10.0/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to mirrors.coreix.net:http: [IP: 85.13.241.50 80]

The MariaDB download site says that the repos should be:

    deb http://mirrors.coreix.net/mariadb/repo/10.0/ubuntu trusty main
    deb-src http://mirrors.coreix.net/mariadb/repo/10.0/ubuntu trusty main

So it looks like `dists/trusty/main/i18n/Translation-en_US` is coming from the `mariadb_version` variable which is setup in `roles/mariadb/defaults/main.yml`. I couldn't track down how the playbook was selecting the closest mirror for the MariaDB Ubuntu repos or how it was overriding the `mariadb_version` variable.

**Comment by swalkinshaw** [comment]
Those repos failing aren't the main ones. We are adding the correct ones [here](https://github.com/roots/bedrock-ansible/blob/517be2a88318de51f51397066575ab07fae825a1/roles/mariadb/tasks/main.yml#L9-L10)

`mariadb_dist ` = `trusty` set [here](https://github.com/roots/bedrock-ansible/blob/517be2a88318de51f51397066575ab07fae825a1/group_vars/all#L3).

Those failures you get are "sub" repos that are fetched after the main ones are added. I've actually had those errors before as well once or twice but they went away on their own. Have you tried again since then? Or maybe another mirror?
