### ISSUE TITLE
Clarify deployment workflow

### ISSUE THREAD

**Issue by louim** [roots/bedrock-ansible#201]
Hello!
Would it be possible to explain de deployment process a bit more? Does this line: https://github.com/roots/bedrock-ansible/blob/master/group_vars/production#L8 should be replaced by my Bedrock Wordpress project? does it deploy from git or from local code? How do we deal with deploying from specific branch? We normally have a `develop`, a `staging` and a `production` branch. how do I match thoses with the environments?

Thanks!!!

**Comment by fullyint** [comment]
@louim This is probably a question for the forums at https://discourse.roots.io/ rather than this bug tracker, but here are some comments.

Yes, in typical usage, `repo` should be your bedrock project (most likely with your roots/sage theme included), in a remote repo such as at github, bitbucket, etc. See these [additional comments](https://discourse.roots.io/t/what-does-bedrock-ansible-deploy-and-what-doesnt-it/3625/9) regarding `repo`.

You can deploy a specific branch. To deploy a branch named "production", for example: 
`ansible-playbook -i hosts/production deploy.yml --extra-vars "site=example.com branch=production"`
You'll see that [the `branch` variable](https://github.com/roots/bedrock-ansible/blob/ff967d15459280b4b1cdbed92c7c376cf6207038/roles/deploy/defaults/main.yml#L6) provides a value to the `project_version` variable, which normally defaults to `master`. Then, the [`project_version` variable](https://github.com/roots/bedrock-ansible/blob/ff967d15459280b4b1cdbed92c7c376cf6207038/roles/deploy/tasks/main.yml#L8) specifies the desired branch at the moment of cloning.

**Comment by louim** [comment]
@fullyint I agree that the question seems a little more forum oriented, however, I believe it has its place here, to keep track of how to improve the documentation. I think that settings like these should be documented, so people can use the project without having to dig in the roles. I'll gladly create a wiki page or a pull request to the main readme to document those things. Which one is the perferred way?

Speaking of the branch setting, I think that the `branch` variable would be more appropriate as `project.branch` so it could be set site by site in the config, and it  would be less confusing. I believe most of the use case involve setting a specific branch per environment, instead of specifying it at deploy time.

**Comment by swalkinshaw** [comment]
@louim good point about the branch. Agreed that moving into the `project` is ideal. That way you'll almost never have to specify the branch depending on your workflow.

Would you like to do a PR for this?

Let's keep this issue going for now and we can determine what to document/Wiki depending on what comes out of this discussion.

**Comment by fullyint** [comment]
Good points @louim. I'd be inclined to have the `project.branch` optional so it could be left out of `group_vars/<environment>` files and default to `master`. You could adjust [this line](https://github.com/roots/bedrock-ansible/blob/ff967d15459280b4b1cdbed92c7c376cf6207038/roles/deploy/defaults/main.yml#L6) to be 
`project_version: "{{ project.branch | default('master') }}"`

I imagine you'd also add a note about the `project.branch` option to the README, and you might want to mention that this `branch` option accepts not just branch name, but also tags or SHAs (ref: [git_module](http://docs.ansible.com/git_module.html)).

**Comment by louim** [comment]
Pull request opened. While we are discussing documentation, I would like to discuss something: The wiki. Personnally, I find the information it contain really great, but I prefer having that information right in the project. This has three main advantages:

* All the documentation is kept with the project, so once you have cloned, you have all you need in the repo without the need to go to github to find something.
* When you fork the project, you donc get the wiki. So If I want to fork Bedrock-Ansible, all the information follows the project without having to copy the wiki or to refer to the original one.
* Having the information in the project makes it more up to date and keeps it in sync with the code, since when you add a new feature / modify something you dont have to go to a separate place to document.

I think the wiki is best suited to complementary information, tips and tricks, examples and general informations. The core documentation should stay with the project. A readme in the related role (for example [the Fail2ban readme](https://github.com/roots/bedrock-ansible/blob/master/roles/fail2ban/README.md)), referenced from the main readme so you can easily navigate in the documentation would be the best I think.

**Comment by retlehs** [comment]
the wiki is temporary until the docs are moved onto the roots.io site. that discussion can happen off of github and on our discourse.
