### ISSUE TITLE
Debian 7.x

### ISSUE THREAD

**Issue by saturday** [roots/bedrock-ansible#230]
I'm in the process of setting up Bedrock-Ansible with a Debian 7 box instead of the default box. 

I'm running into a few issues. Namely, getting MariaDB installed, which I fixed, and Installing php 5.6 via the ondrej ppa `msg: Invalid repository string: ppa:ondrej/php5-5.6`.

Does Roots recommend against using anything but Ubuntu along side bedrock-ansible? It's not entirely clear.

**Comment by swalkinshaw** [comment]
The only reason we require Ubuntu is because the playbooks are designed for it (as you found it). It just requires more work (and testing) to get it working on Debian and potentially others like CentOS so we just avoid that by going Ubuntu only.

I'd be open to supporting Debian though if it doesn't require too many changes.

**Comment by saturday** [comment]
Would you like me to share the work I've done once I complete whatever is required to support Debian 7? By the way, I enjoyed the Changelog interview. It was timely for me.

**Comment by austinpray** [comment]
I am definitely in favor of making things more cross platform.

One idea to solve the PHP problem is to use https://github.com/CHH/phpenv to install PHP rather than relying on package managers.

@saturday what issue were you having with installing MariaDB? I've never had a problem installing MariaDB on debian. I'm not sure what bedrock-ansible does different than [the instructions on the website](https://downloads.mariadb.org/mariadb/repositories/#mirror=digitalocean-sfo&distro=Debian&distro_release=wheezy--wheezy&version=5.5).

**Comment by swalkinshaw** [comment]
@saturday thanks!

Yeah I'd be interested in seeing the changes. Maybe you could push your fork and then potentially do a PR.

**Comment by saturday** [comment]
@austinpray All I really did was change the mirror to mariadb.mirror.rafal.ca and updated the package url in `roles/mariadb/main.yml` to use debian instead of ubuntu:

`deb http://{{ mirror }}//repo/{{ version }}/debian {{ mariadb_dist | default(ansible_distribution_release) }} main`

Regarding PHP, I'm using `deb http://packages.dotdeb.org wheezy-php56 all` instead of the ppa; however I'm running into an unmet dependency issue that I still need to look at.

**Comment by saturday** [comment]
I managed to get it working with Debian 7.6 with a one relatively major exception. I ran into an issue with xdebug and simply commented out that vendor role. I did all of this in a non-forked private repository, so I'll have to share the code at a later date (it's a relatively simple process).

Here are the high-level steps without specific details:

1. Update the MariaDB mirror and URL
2. Update the php55-6 PPA to a deb package.
3. Remove the xdebug role entirely - I'm going to revisit this issue shortly.
4. Update Nginx PPA to use deb package.
5. Create `/etc/nginx/site-enabled`
6. Get composer via curl and move to `/usr/local/bin`. Remove default apt based install.
7. Add `  apt_repository: repo="deb http://ftp.hosteurope.de/mirror/packages.dotdeb.org/ wheezy all" update_cache=yes` to the Memcache main.yml. Also, add `force = yes` to Memcache install task.
8. Create `/etc/nginx/sites-available
9. Change `php5-fpm-wordpress.sock` to `php5-fpm.sock` in the wordpress.conf.j2 and php-fpm.conf.j2 files.
